before_install:
- openssl aes-256-cbc -K $encrypted_b6b540ec2d3b_key -iv $encrypted_b6b540ec2d3b_iv -in .deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
addons:
  ssh_known_hosts:
  - cmr-dev.jembi.org
  - cmr-staging.jembi.org
deploy:
- provider: script
  script: ssh bahmni_support@cmr-dev.jembi.org 'cd ~/git/cameroon-bahmni-config/;git
    pull;'
  on:
    branch: COMRS-118
- provider: script
  script: ssh bahmni_support@cmr-staging.jembi.org 'cd ~/git/cameroon-bahmni-config/;git
    pull;'
  on:
    branch: COMRS-118
