language: minimal
before_install:
- openssl aes-256-cbc -K $encrypted_b6b540ec2d3b_key -iv $encrypted_b6b540ec2d3b_iv -in .deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
addons:
  ssh_known_hosts:
  - cmr-dev.jembi.org
  - cmr-staging.jembi.org
deploy:
- provider: script
  script: ssh bahmni@cmr-dev.jembi.org 'cd ~/git/cameroon-bahmni-config;git reset --hard;git checkout dev;git pull;mysql -u root -ppassword openmrs < openmrs/apps/reports/PECG_REPORT/sql/report_util_functions.sql;mysql -u root -ppassword openmrs < openmrs/apps/reports/PECG_REPORT/sql/indicator_functions.sql;'
  on:
    branch: dev
- provider: script
  script: ssh bahmni@cmr-staging.jembi.org 'cd ~/git/cameroon-bahmni-config;git reset --hard;git checkout staging;git pull;mysql -u root -ppassword openmrs < openmrs/apps/reports/PECG_REPORT/sql/report_util_functions.sql;mysql -u root -ppassword openmrs < openmrs/apps/reports/PECG_REPORT/sql/indicator_functions.sql;'
  on:
    branch: staging